### ISSUE TITLE
The image did not load during the first initialization App

### ISSUE THREAD

**Issue by IOSBelief** [7mada123/disposable_cached_images#1]
None of the images were loaded when the app was first initialized on the iPhone

**Comment by LiuYongHeng** [comment]
[VERBOSE-2:dart_isolate.cc(1111)] Unhandled exception:
FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/96862137-7ACA-43F0-9CAB-BB215E33DA64/Library/Caches/images_cache/cache_keys.json' (OS Error: No such file or directory, errno = 2)


when the app was first initialized on the iPhone

**Comment by LiuYongHeng** [comment]
[VERBOSE-2:dart_isolate.cc(1111)] Unhandled exception:
FileSystemException: Cannot open file, path = '/var/mobile/Containers/Data/Application/96862137-7ACA-43F0-9CAB-BB215E33DA64/Library/Caches/images_cache/cache_keys.json' (OS Error: No such file or directory, errno = 2)

when the app was first initialized on the iPhone

**Comment by 7mada123** [comment]
Hello @IOSBelief

Can you provide more information, dose the images load on the second launch and did you see an error message on the debug console ?
