### ISSUE TITLE
New memory management in Flutter 3.7

### ISSUE THREAD

**Issue by mohamed-yahyaoui** [7mada123/disposable_cached_images#7]
Did this feature introduced in Flutter 3.7 https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c#2507 make this package unnecessary?

**Comment by 7mada123** [comment]
Hi Mohamed,
This new feature is solely focused on improving Dart's garbage collector and will not address the image memory issue. However, this package tries to solve this issue [#62107](https://github.com/flutter/flutter/issues/62107). Once the Flutter team resolves it, this package will no longer be necessary.

**Comment by mohamed-yahyaoui** [comment]
Thanks for the response and the packge
